package.json
src/components/Atoms/RichText/RichText.js
src/components/Atoms/RichText/RichText.test.js
yarn.lock

Type: fix
Dompurify will not work with gatsby built app. We will have to sanitise the content at the app level.

fix: Remove dompurify not working with gatsby

---

docs/utils.md
src/index.js
src/theme/shared/zIndex.js

Type: feature
To avoid using random `z-index` and possible positioning conflicts.
_Z Index_
`import { zIndex } from '@comicrelief/component-library';`
how to use in your styled component
```
const Component = styled.span'
${zIndex('high')};
';
```

feat: add zindex helper

---

src/components/Molecules/Header/Nav/Nav.js

Type: patch
Fixes #79 
- Fixes `ReferenceError: window is not defined` during Gatsby build as components are rendered server-side where `window` isn't defined. 
- Solved by accessing `window` after component has mounted or checking if `window` is not `undefined` before accessing it.

fix: #79 - window not defined

---

src/components/Atoms/Checkbox/Checkbox.test.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/RadioButton/RadioButton.test.js
src/components/Atoms/SelectField/SelectField.test.js
src/components/Atoms/Text/Text.js
src/components/Atoms/Text/Text.md
src/components/Atoms/Text/Text.test.js
src/components/Atoms/TextArea/TextArea.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/CookieBanner/CookieBanner.test.js
src/components/Molecules/EmailSignUp/EmailSignUp.test.js
src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/components/Molecules/SingleMessage/SingleMessage.test.js
src/theme/crTheme/theme.js
src/theme/shared/fontFamilies.js

Type: patch
Fixes #133 
- add fontFamilies to shared theme
- add font family as a prop to Text component and get font family from theme
- update all tests where Text is used

font-family as prop in Text component

---

src/components/Molecules/CookieBanner/CookieBanner.js
src/components/Molecules/CookieBanner/CookieBanner.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#61 specifically https://comicrelief-contentful-lighthouse.s3.amazonaws.com/61-cookie/index.html

fix: cookie banner SEO error due to not using descriptive text in link

---

src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js
src/theme/shared/zIndex.js

Type: patch
Fixes comicrelief/comicrelief-contentful#278
- Increase menu z-index to raise it above play button.

fix: header menu getting hidden behind play button on small devices

---

src/theme/shared/global.css

Issue is here: https://github.com/comicrelief/comicrelief-contentful/issues/448

H1 text cutting off on schools fundraising ideas pages on iPads Pro portrait view

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Molecules/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/Membership/Membership.test.js
src/components/Molecules/SearchInput/SearchInput.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#490
- Accessibility fails when input attributes are present in label as well, so extra ones are now removed from label.

fix: Remove label confusing attributes

---

src/components/Organisms/Header/Nav/Nav.js
src/components/Organisms/Header/data/data.js
src/components/Organisms/Header/header.test.js

Type: patch
https://deploy-preview-279--cr-component-library.netlify.app/#!/Header/3
now we have `haspopup` only for items with submenus and `noopner` for external links

Add noopener to nav for external links

---

src/components/Atoms/Input/Input.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

Fixes #290 
Type: patch
- Alters the Input component so that props captured by `...rest` (including event handlers) are only added to the InputField element
- Adds className prop to Input and passes this to the outer element, Label, only (previously className was being added to both elements)

Fix: Issue with Input component duplicating props & adding event handlers twice

---

src/components/Molecules/SchoolLookup/SchoolLookup.js
src/components/Molecules/Typeahead/Typeahead.js

i.e. in the descriptions when you expand 'Props & Methods'

fix: Changing prop type comments so they show up in styleguide

---

src/components/Organisms/MarketingPreferences/InputController.js

Otherwise, you get 'A component is changing an uncontrolled input of type text to be controlled' warnings
(Note that defaultValues passed into the useForm hook will still override this inline default)

fix: react-hook-form Controller text inputs require a defaultValue prop

---

src/components/Atoms/Button/Button.js
src/components/Atoms/Checkbox/Checkbox.js
src/components/Atoms/Input/Input.js
src/components/Atoms/RadioButton/RadioButton.js
src/components/Atoms/Select/Select.js
src/components/Atoms/TextArea/TextArea.js

It can be useful / necessary to attach refs to form inputs to access their state / values
Therefore it's probably best if any component library forwards refs on form inputs
Additionally, we have started using `react-hook-form` which heavily encourages you to use `uncontrolled` inputs (I think mostly for performance reasons). To do so, we need to forward refs to the underlying inputs.
Once we have done this, we should be able to simplify the `MarketingPreferences` component and the new fundraise form a bit (e.g. we won't need to use the `Controller` component)

feat: Forwarding refs on input components

---

cypress/integration/components/Atoms/Checkbox.spec.js
src/components/Atoms/Checkbox/Checkbox.js
src/components/Atoms/Checkbox/Checkbox.md

Closes: https://github.com/comicrelief/component-library/issues/339
Can either do this, or export the checkbox input as its own component?

feat: update checkbox to accept children (if no label supplied)

---

src/components/Atoms/TextArea/TextArea.js
src/components/Atoms/TextArea/TextArea.md
src/components/Atoms/TextArea/TextArea.test.js

Type: patch
Fixes #387
Fixed height prevents the use of the 'rows' attribute

fix: Remove fixed height from TextArea component

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/Input.md

Wanted to be able to style the label as per Ruby's designs, without having to use HTML strings

feat: Accept React component for <Input> label prop (as well as strings)

---

cypress/integration/components/Molecules/SchoolLookup.spec.js

I think we just need to get rid of these tests
They are costing too much time when they keep failing

Remove SchoolLookup tests that keep failing

---

src/components/Organisms/MarketingPreferencesDS/_MarketingPreferencesDS.js
src/components/Organisms/MarketingPreferencesDS/_NoMessage.js

Something that I noticed during work for https://github.com/comicrelief/comicrelief-contentful/pull/1102, this brings in the same improvements made to MP messaging that were added to the Donation version just before RND22

fix: improve MP messaging, inline with Donate version

---

src/components/Organisms/MarketingPreferencesDS/_CheckAnswer.js
src/components/Organisms/MarketingPreferencesDS/_MarketingPreferencesDS.js

Type: patch
Fixes #https://comicrelief.atlassian.net/browse/ENG-1520
- As per the ticket, when a MP option is toggled on, a value is supplied, then then toggle off again, we want to ensure we're not accidentally able to submit unvalidated values.
- Sooooo we're resetting all fields associated with the checkbox option

fix: Reset associated MP fields when option unselected

---

src/index.js

Rename the export name of `Radio` to `RadioButton`
Cleans up the exports to keep this inline with the rest of the exports, also prevents any confusion over the naming.

fix: rename Radio to RadioButton.

---

src/components/Atoms/Select/Select.js
src/components/Atoms/Select/__snapshots__/Select.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap

- Adds the `optional` label prop to the select component.
- Adds the `required` flag to the select component.
Allows for more clarity when select fields are not required.

feat: add optional label and required prop to select component

---

src/components/Atoms/Checkbox/Checkbox.js
src/components/Atoms/Checkbox/Checkbox.test.js

Adjust span spacer as part of the Checkbox.js component, as it creates an issue with long labels.
As part of new FSU journey, the checkbox on step 2, terms and conditions, shrinks to unusable size on mobile view.
[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-1764)

fix: adjust span spacer as creates issue with long labels

---

src/components/Atoms/RadioButton/RadioButton.js
src/components/Atoms/RadioButton/RadioButton.test.js

Same fix as with the checkbox component, stops the spacing from collapsing.
Same issue as with the checkbox component, causing the spacing to collapse with a larger amount of text:

fix: fix no spacing issue on radio button

---

src/components/Atoms/Logo/Logo.js
src/components/Atoms/Logo/Logo.test.js
src/components/Organisms/Header/Header.style.js

I overlooked the fact that the CL is actually adding padding to its examples:
So, within the real context:
IT LOOKS BAD
Same ticket as before, although I'm not going to _hyperlink_ it, as it'll annoyingly close the ticket AGAIN before I get a chance to get int into CR properly - comicrelief.atlassian.net/browse/ENG-1784

fix: fix header for in-situ usage

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/GivingSelector/GivingSelector.js
src/theme/shared/size.js

We're currently using this in the CRcom integration of the Promo without any issues, so I'm hoping this'll solve the issue we were seeing :
(Slack thread [here](https://comicrelief.slack.com/archives/C041U74BL/p1665671885014529))
I can confirm this is due to the 'isDesktop' variable not being set in time for initial render; I could recreate this locally by removing the variable assign.

fix: use alternative Media Query function

---

src/components/Organisms/Header/Nav/Nav.js

Add chevrons to mobile view.
Got wires crossed and thought they were only for dekstop view.
https://comicrelief.atlassian.net/browse/ENG-1740

feat: add chevrons to mobile view as well 

---

src/components/Organisms/EmailSignUp/EmailSignUpForm.js
src/components/Organisms/EmailSignUp/_EmailSignUp.js

Sets a specific custom error called 'formError' that will be used for capturing errors as part of the submit callback. Allows us to be explicit about what errors we wish to show.
Previous implementation was also showing field errors in certain situations, as these should be displayed in the field itself, it could be confusing so this clears that up.

fix: Make ESU error handling more explicit

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Donate.style.js
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap

- Adds textColor field.
- Adds overlayColor field (for desktop overlay colour).
- Adds a buttonColor field to allow for future theming of the submit button.
- Changes backgroundColour to refer to mobile/tablet background colour.
- Updates snapshots.
The theming work for the Donate widget requires some updates and changes to allow for some more fine-grained theming of the widget on both desktop and mobile/tablet views.
As per Jira: [ENG-2069]
[ENG-2069]: https://comicrelief.atlassian.net/browse/ENG-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updates to `Donate` component to allow for more advanced theming

---

src/components/Organisms/MarketingPreferencesDS/MarketingPreferencesDSForm.js
src/components/Organisms/MarketingPreferencesDS/_CheckAnswer.js

Adds in a check so that we're only clearing out MP field values when it's a scenario when the user is being shown the field, not a "pass the value behind the scenes, keep the field hidden" scenario.
Bug raised
[Link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-2191)

fix: make MP field values persist when hidden

---

src/utils/whiteListed.js

Adds in the embed URL domain for Shorthand stories, to be used on CRcom in the new HTML Paragraph; this way there's a level of protection about what people can embed
For ze stories, and for ze safety.
No ticket per se, but related to https://comicrelief.atlassian.net/browse/ENG-2228 as discussed

feat: updates whitelist with Shorthand stories embed URL domain 

---

src/components/Molecules/CardDs/CardDs.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap
src/components/Molecules/SingleMessageDS/SingleMessageDs.js
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap

Just makes the CTA copy available to the GA when the user clicks on the img link, rather than the button; that way, Hiral and co. can better track the journey in relation to the content.
Better GA insight
No ticket, just had a convo and it came up

feat: add data-attribute to CardDS & SingleMsgDS for GA reasons

---

src/components/Molecules/CardDs/CardDs.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap
src/components/Molecules/SingleMessageDS/SingleMessageDs.js
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap

Adds a data-attribute to the Link button itself (on SingleMsgDS and CardDS content tyles) for use in GA, but also updates the naming convention so GA can determine _which_ link (button or img) has been clicked on.
Tracking user interactions n stuff
https://comicrelief.atlassian.net/browse/ENG-2606

fix: add GA data attribute to button itself

---

src/components/Molecules/VideoBanner/VideoBanner.js
src/components/Molecules/VideoBanner/VideoBanner.md

Forces muting of videos of autoplaying
[Tell us why this is required from a business/product perspective.](https://developer.chrome.com/blog/autoplay/)
No ticket, just an bug thrown in CR PR

fix: handle autoplay muting Video banners

---

src/components/Molecules/Promo/Promo.js
src/components/Molecules/Promo/Promo.md
src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/_PromoVideo.js
src/components/Molecules/Promo/_PromoVideoButton.js
src/components/Molecules/Promo/_PromoVideoButton.style.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap

Some additions and simplification to make the new functionality better fit for purpose
Good content = nice
No ticket, just an extension of the original rly

fix: Promo Video updates

---

src/components/Organisms/ImpactSlider/ImpactMoneybuys.style.js
src/components/Organisms/ImpactSlider/ImpactSlider.js
src/components/Organisms/ImpactSlider/ImpactSlider.md
src/components/Organisms/ImpactSlider/ImpactSlider.style.js

Adds an additional bgcolour prop that I missed; the real thing will only allow white/grey in situ, but I've made this as flexible and future proof as possible
Missed this requirement in the original PR
Nae ticket

fix: additional bg colour prop in ImpactSlider

---

src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap

Removes inaccurate button logic that resulted in button copy that didn't actually _mention_ 'monthly' for "no moneybuy" Monthly donate widgets
To fix some terrible UX
Piggybacking off https://github.com/comicrelief/comicrelief-contentful/pull/1437 for https://comicrelief.atlassian.net/browse/ENG-2

fix: remove inaccurate Donate widget button copy logic

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

Uses the same padding logic from the CardsDS, Cards and Donate paragraph work to add the same options to Single Msg component (on LG only)
Flexibility and improved aesthetics for heavy bits of content
comicrelief.atlassian.net/browse/ENG-3087

feat: Single Message padding options on LG

---

babel.config.js
package.json
yarn.lock

e.g.
or
Move `dependencies` that don't need to be published (i.e. supporting dependencies, those not referenced in the codebase) to `devDependencies`.
Reducing the list of `dependencies` reduces the weight of the library, improving performance.

chore: Move dependencies to devDependencies (to reduce library weight)

---

package.json

e.g.
or
Remove the `postinstall` step as its unnecessary (the `dist` folder is packaged with the build) and it will fail on environments where the `devDependencies` haven't been installed (i.e. anywhere where `@comicrelief/compontent-library` is a dependency).
See above

fix: Tweak build step after deps change

---

package.json
yarn.lock

e.g.
or
This PR upgrades Axios to v1 (including some config tweaks to avoid testing errors from that upgrade) 
The Axios dependency was on v0.2* which has security alerts.

fix: Upgrade Axios to v1 (security)

---

src/components/Organisms/MarketingPreferencesDS/_DefaultCopy.js

_Could_ override this prop within CRcom, but it make sense to take care of this fully at the source.

fix: open MP copy links in new tab

---

src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap
src/index.js

Just so we can use these in the fancy Richtext convertor

feat: export Ext. and Int. link icons for use in new Donate

---

src/components/Atoms/TextInputWithDropdown/TextInputWithDropdown.js
src/components/Atoms/TextInputWithDropdown/TextInputWithDropdown.style.js
src/components/Molecules/SchoolLookup/SchoolLookup.js

e.g.
or
There's a fixed black border around the schoolsLookup compo, and no close-on-click-outside behaviour. This fixes both.
The donate FE rebuild doesn't need the border, and needs close on click outside.
[DF-148]
[DF-148]: https://comicrelief.atlassian.net/browse/DF-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: DF-148 schools lookup refactor

---

src/components/Atoms/TextInputWithDropdown/TextInputWithDropdown.js

Bug DF-130 highlights that we have lost previous functionality, where dropdown lists (such as in the postcode lookup) should close results if you click the first descriptive placeholder line that appears at the top of the results, such as 'Please select a school'
Keep app behaviour consistent.
[DF-130]
[DF-130]: https://comicrelief.atlassian.net/browse/DF-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: DF-130: Closes a dropdown list when the placeholder line is clicked

---

src/components/Organisms/Header2025/Header2025.md
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.js
src/components/Organisms/Header2025/data/data-live--minimal.js

When trying to implement the new nav in a CRcom build (which currently uses a smaller number of nav items than expected), it threw up a few bugs; this address them.

fix: handle fewer items in Header2025

---

src/components/Atoms/SocialIcons/Icon/Icon.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.style.js

Turns out this flew-grow width DOES work _dynamically_, so it won't interfere with the header icon hover width animation stuff.

fix: use all available space for More Nav item

---

README.md
playwright/components/atoms/checkbox.spec.js
src/components/Atoms/Checkbox/Checkbox.md

Accidentally pushed to master midway, rather than a PR branch; fixing here it now.

fix: associate checkboxes with their labels as tests can't target hidden checkboxes

---

src/components/Organisms/Footer/Footer.js

Looks like someone previously put that prop in the wrong place...
This **_now_** allows us to completely ignore the allowlist (which governs internal vs. external footer links) so Donate can mark every CRcom footer link as 'external', opening in a new tab

fix: fixes footer 'allowlist' override

---

src/components/Organisms/MarketingPreferencesDS/MarketingPreferencesDS.style.js

Corrects checkbox (& parent container) outline colour to match our designs
QA design feedback
[DF-376]
[DF-376]: https://comicrelief.atlassian.net/browse/DF-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Corrects outline colour for marketing checkboxes and their containers
