comicrelief/component-library

docs/utils.md
src/index.js
src/theme/shared/hideVisually.js
styleguide.config.js

feat: Add hideVisually util

---

src/components/Atoms/Picture/Picture.js
src/components/Atoms/RadioButton/RadioButton.js
src/components/Atoms/RadioButton/RadioButton.test.js
src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.test.js
src/theme/shared/fonts.css

BREAKING CHANGE: Single message uses children as props
Type: feature
Fixes #29

feat: Single message copy as children props

---

package.json
src/components/Atoms/Picture/Picture.js
src/components/Atoms/Picture/Picture.md
src/components/Atoms/Picture/Picture.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.test.js
src/styleguide/ThemeWrapper.js
src/styleguide/data/data.js
yarn.lock

Type: patch
Fixes #45
Add lazyload to Picture

Lazyload images

---

src/components/Atoms/Link/Link.js
src/components/Atoms/Link/Link.md
src/components/Atoms/Link/Link.style.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/Card/Card.js
src/components/Molecules/Card/Card.md
src/components/Molecules/Card/Card.test.js
src/index.js
src/theme/shared/fonts.css

Type: patch
Fixes #33 
Card Component

Card with children props

---

src/components/Molecules/Header/Header.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/data/data.js

Improve navigation menu

---

src/components/Molecules/Header/Burger/BurgerMenu.js
src/components/Molecules/Header/Burger/BurgerMenu.style.js
src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/header.test.js
src/index.js

Hamburger menu animation

---

src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/data/data.js

Update nav menu ( submenu map logic)

---

src/components/Molecules/Header/Header.js
src/components/Molecules/Header/header.test.js

Trigger release

---

package.json
src/components/Molecules/Header/Burger/BurgerMenu.style.js
src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/data/data.js
src/components/Molecules/Header/header.test.js
yarn.lock

Update nav menu

---

src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/header.test.js

Fix header

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.test.js
yarn.lock

Type: feat
Fixes #67 
Add two more variations to SM
https://deploy-preview-68--cr-component-library.netlify.com/#singlemessage

Single Message variations

---

.eslintrc
src/components/Atoms/Link/Link.js
src/components/Atoms/Link/Link.test.js
src/components/Atoms/Logo/Logo.js
src/components/Atoms/Logo/Logo.test.js
src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/SingleMessage/SingleMessage.test.js

Improve nav a11y

---

src/components/Atoms/Checkbox/Checkbox.test.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/Link/Link.style.js
src/components/Atoms/RadioButton/RadioButton.test.js
src/components/Atoms/SelectField/SelectField.test.js
src/components/Atoms/Text/Text.js
src/components/Atoms/TextArea/TextArea.test.js
src/components/Molecules/CookieBanner/CookieBanner.js
src/components/Molecules/CookieBanner/CookieBanner.md
src/components/Molecules/CookieBanner/CookieBanner.style.js
src/components/Molecules/CookieBanner/CookieBanner.test.js
src/components/Molecules/Header/header.test.js
src/theme/crTheme/colors.js

Cookie Banner

---

src/components/Molecules/Header/Header.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/Nav/Nav.style.js

Header: hook fix warning

---

src/components/Atoms/RichText/RichText.md
src/components/Molecules/DoubleCopy/DoubleCopy.js
src/components/Molecules/DoubleCopy/DoubleCopy.md
src/components/Molecules/DoubleCopy/DoubleCopy.style.js
src/components/Molecules/DoubleCopy/DoubleCopy.test.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/header.test.js
src/index.js

 Copy copy SM

---

docs/utils.md
src/index.js
src/utils/whiteListed.js
src/utils/whiteListed.test.js

feat: Add whitelisted util

---

src/utils/whiteListed.js

fix: improve whitelist check

---

src/index.js

fix: add missing Footer export

---

src/utils/whiteListed.js

fix: improve Link whitelist check

---

src/components/Molecules/PartnerLink/PartnerLink.js
src/components/Molecules/PartnerLink/PartnerLink.md
src/components/Molecules/PartnerLink/PartnerLink.style.js
src/components/Molecules/PartnerLink/PartnerLink.test.js

Partner card link 

---

src/components/Molecules/Footer/Nav/Nav.js

Def. window val for webpack

---

src/components/Atoms/Pagination/List/List.js
src/components/Atoms/Pagination/Pagination.js
src/components/Atoms/Pagination/Pagination.test.js
src/components/Atoms/Pagination/__snapshots__/Pagination.test.js.snap
src/components/Molecules/ArticleTeaser/ArticleTeaser.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.md
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#8
- Center pagination
- Hide pagination when there is no pages
- Add copy to Article teaser
- Allow image resize in Article teaser

Contentful search

---

src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/PartnerLink/PartnerLink.style.js
src/components/Molecules/PartnerLink/PartnerLink.test.js

Update header style

---

src/components/Molecules/SearchResult/SearchResult.js
src/components/Molecules/SearchResult/SearchResult.md
src/components/Molecules/SearchResult/SearchResult.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/index.js

Fixes comicrelief/comicrelief-contentful#8

feat: Add search result molecule

---

src/components/Molecules/Footer/Footer.js
src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Footer/Nav/Nav.js
src/components/Molecules/Footer/data/data.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/data/data.js
src/components/Molecules/Header/header.test.js
src/utils/NavHelper.js

Fix: update Footer and Header menus to reflect how Contentful produces menus

---

src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/SearchInput/SearchInput.js
src/components/Molecules/SearchInput/SearchInput.md
src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/SearchInput/assets/search.svg
src/index.js

feat: Search  input

---

src/components/Molecules/PartnerLink/PartnerLink.js
src/components/Molecules/PartnerLink/PartnerLink.md
src/components/Molecules/PartnerLink/PartnerLink.style.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchInput/SearchInput.test.js

Partner link card update

---

src/components/Molecules/PartnerLink/PartnerLink.js
src/components/Molecules/PartnerLink/PartnerLink.md
src/components/Molecules/PartnerLink/PartnerLink.style.js
src/components/Molecules/PartnerLink/PartnerLink.test.js

Partner Link style update 

---

src/components/Molecules/EmailSignUp/EmailSignUp.js
src/components/Molecules/EmailSignUp/EmailSignUp.md
src/components/Molecules/EmailSignUp/EmailSignUp.style.js
src/components/Molecules/EmailSignUp/EmailSignUp.test.js
src/index.js

Type: patch
Fixes comicrelief/comicrelief-contentful#55
- Allow more control on how ESU looks
- Expose it

ESU component

---

src/index.js

fix: export ShareButton

---

src/components/Molecules/ShareButton/ShareButton.js

fix: check for Window obj in sharebuttons

---

src/components/Molecules/SearchResult/SearchResult.js
src/components/Molecules/SearchResult/SearchResult.md
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap

Update search result

---

src/components/Molecules/Header/Burger/BurgerMenu.style.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js

 Burger menu bug

---

src/components/Molecules/Card/Card.js
src/components/Molecules/Card/Card.test.js

Card updates

---

src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.test.js

Fix single message layout #131

---

src/components/Molecules/Card/Card.js
src/components/Molecules/Card/Card.md
src/components/Molecules/Card/Card.test.js

Type: fix
Issue: the image  is not displayed on Card component

fix: fix card image

---

src/components/Molecules/Card/Card.js
src/components/Molecules/Card/Card.md

Handle height & width of image

---

src/components/Molecules/Card/Card.js

fix: extend card style

---

src/components/Atoms/Link/Link.js
src/components/Atoms/Link/Link.style.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.md
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/theme/crTheme/linkStyles.js

Update article teaser: press release

---

src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Footer/Nav/Nav.js
src/components/Molecules/Footer/data/data.js
src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/header.test.js
src/utils/internalLinkHelper.js

fix: Format any internal links to correct root path

---

src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/SingleMessage.test.js
src/theme/shared/global.css

Single msg vh fix

---

src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/SingleMessage.test.js

fix: flex grow

---

src/components/Atoms/Text/Text.js
src/components/Atoms/Text/Text.md
src/components/Atoms/Text/Text.test.js
src/components/Atoms/Text/__snapshots__/Text.test.js.snap

Type: feat
Fixes #159
- Add height to text.

Text height

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/Picture/Picture.test.js
src/components/Atoms/RadioButton/RadioButton.js
src/components/Atoms/RadioButton/RadioButton.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/CookieBanner/CookieBanner.js
src/components/Molecules/CookieBanner/CookieBanner.test.js
src/components/Molecules/EmailSignUp/EmailSignUp.test.js
src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/components/Molecules/SingleMessage/SingleMessage.test.js
yarn.lock

Snaps undefined label issues

---

src/components/Molecules/EmailSignUp/EmailSignUp.js
src/components/Molecules/EmailSignUp/EmailSignUp.test.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap

fix: handle vanilla esu form submission

---

src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

Full Image Single Message mobile

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap
yarn.lock

Single message 50:50

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

fix: handle IDs dynamically to work with prebuild Gatsby pages

---

src/components/Molecules/Membership/Form/Form.js
src/components/Molecules/Membership/Membership.style.js
src/components/Molecules/Membership/Membership.test.js

Membership update: fix form's width auto scaling  with content

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

Single msg full image update

---

src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/Nav/Nav.style.js
src/components/Molecules/Header/header.test.js

nav spacing fix

---

src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
yarn.lock

ESU close bug issue

---

src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

fix: single message padding and height fix

---

src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js

Update search icon

---

src/components/Molecules/Header/Nav/Nav.js
src/components/Molecules/Header/data/data.js
src/components/Molecules/Header/header.test.js

Single menu link

---

src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Footer/Nav/Nav.style.js

footer menu dropdown arrows needs alignment on mobile devices 

---

src/components/Atoms/Input/input.test.js
src/components/Atoms/Link/Link.style.js
src/components/Atoms/Link/Link.test.js
src/components/Atoms/SelectField/SelectField.test.js
src/components/Atoms/Text/Text.js
src/components/Atoms/Text/__snapshots__/Text.test.js.snap
src/components/Atoms/TextArea/TextArea.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/Card/Card.js
src/components/Molecules/Card/__snapshots__/Card.test.js.snap
src/components/Molecules/CookieBanner/CookieBanner.test.js
src/components/Molecules/EmailSignUp/EmailSignUp.style.js
src/components/Molecules/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/Membership/Membership.test.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/components/Molecules/ShareButton/ShareButton.style.js
src/components/Molecules/ShareButton/ShareButton.test.js
src/components/Molecules/SingleMessage/SingleMessage.md
src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap
src/theme/crTheme/fontSizes.js
src/theme/shared/global.css
src/theme/shared/spacing.js

fix: Typography sizes

---

src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.style.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap

see issue here: https://github.com/comicrelief/comicrelief-contentful/issues/380

fix for header ESU placeholder font size

---

src/components/Molecules/EmailSignUp/EmailSignUp.js
src/components/Molecules/EmailSignUp/EmailSignUp.md
src/components/Molecules/EmailSignUp/EmailSignUp.test.js
src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.js
src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.md
src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#411

Fix email validation

---

src/components/Atoms/Logo/Logo.js
src/components/Atoms/Logo/Logo.test.js
src/components/Atoms/Picture/Picture.js
src/components/Atoms/Picture/Picture.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/Card/__snapshots__/Card.test.js.snap
src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Header/header.test.js
src/components/Molecules/Membership/Membership.test.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/components/Molecules/SingleMessage/SingleMessage.style.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap

Type: patch
Fixes single msg vertical height resize

fix: vh min height

---

src/components/Molecules/SearchInput/SearchInput.js
src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#483
- Allow extra props like autofocus to be passed to search input
- Use background prop in IE only as mask is not supported there

483 Search accessibility issues

---

src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js

Type: patch
Fixes comicrelief/comicrelief-contentful#501

Fix: Increase search icon contrast ratio against bgd

---

src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap

Type: patch
Fixes comicrelief/comicrelief-contentful#486

fix: ESU header label

---

src/components/Atoms/Link/Link.js
src/components/Atoms/Link/Link.style.js
src/components/Atoms/Link/Link.test.js

Type: patch
Fixes https://github.com/comicrelief/comicrelief-contentful/issues/504

fix: link helper text blank target

---

src/components/Molecules/Membership/Form/Form.js
src/components/Molecules/Membership/Membership.style.js
src/components/Molecules/Membership/Membership.test.js

Type: patch
Fixes #224 
Relates to https://github.com/comicrelief/comicrelief-contentful/issues/479#event-2946584612

Accessibility improvements

---

src/components/Atoms/Logo/Logo.js
src/components/Atoms/Logo/Logo.md
src/components/Atoms/Logo/Logo.test.js
src/components/Molecules/Footer/Footer.js
src/components/Molecules/Footer/Footer.md
src/components/Molecules/Footer/Footer.style.js
src/components/Molecules/Footer/Footer.test.js
src/components/Molecules/Header/Header.js
src/components/Molecules/Header/Header.md
src/components/Molecules/Header/Header.style.js
src/components/Molecules/Header/header.test.js

Type: patch
Issue  is here: https://github.com/comicrelief/comicrelief-contentful/issues/485

Homepage not linked from logo for screen readers

---

src/styleguide/CRLogo.js
styleguide.config.js

Fixes #229 
Preview is here https://deploy-preview-231--cr-component-library.netlify.com/

Fix load logo CL site

---

src/components/Molecules/Membership/Form/Form.js

Issue is here https://github.com/comicrelief/comicrelief-contentful/issues/538
- Issue 1

Prevent membership submission when error message is displayed

---

src/components/Molecules/SingleMessage/SingleMessage.js

Type: patch
Fixes video performance

load player on click

---

src/components/Molecules/ArticleTeaser/ArticleTeaser.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.md
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js

Teaser reDesign

---

src/components/Atoms/Link/Link.style.js
src/components/Atoms/Link/Link.test.js
src/components/Atoms/SocialIcons/Icon/Icon.js
src/components/Atoms/SocialIcons/__snapshots__/SocialIcons.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/HeaderEsuWithIcon.js
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/ShareButton/ShareButton.test.js
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap
src/components/Organisms/CookieBanner/CookieBanner.test.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Footer/Footer.test.js
src/components/Organisms/Header/header.test.js

Fixes https://github.com/comicrelief/comicrelief-contentful/issues/583
Preview env is here https://headless-pr.comicrelief.com/583-ix-button-size-on-ie11/

button styles on CR prod not working as expected on IE11 and iPads

---

src/components/Organisms/Footer/Footer.test.js
src/components/Organisms/Footer/Nav/Nav.style.js
src/components/Organisms/Footer/data/data.js

Fixes #https://github.com/comicrelief/comicrelief-contentful/issues/327

Footer nav items are aligned to the left on IE11 & iPad Pro

---

src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Organisms/Donate/Donate.style.js
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/EmailSignUp/EmailSignUp.js
src/components/Organisms/EmailSignUp/EmailSignUp.style.js
src/components/Organisms/EmailSignUp/EmailSignUp.test.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Form/Form.js
src/components/Organisms/Membership/Membership.style.js
src/components/Organisms/Membership/Membership.test.js

Fixes #266 
Preview https://deploy-preview-267--cr-component-library.netlify.com/#!/EmailSignUp/1

Update ESU form with button type submit

---

src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Organisms/EmailSignUp/EmailSignUp.js
src/components/Organisms/EmailSignUp/EmailSignUp.style.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap

Form input accessibility 

---

src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/dev-data/data-single.js

Type: patch
Fixes giving types bugs

Fix giving types

---

src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/EmailSignUp/EmailSignUp.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Footer/Footer.test.js
src/components/Organisms/Footer/Nav/Nav.js
src/components/Organisms/Header/Nav/Nav.js
src/components/Organisms/Header/header.test.js

Donate widget a11y

---

src/components/Organisms/Header/Nav/Nav.style.js
src/components/Organisms/Header/header.test.js

Fixes is here https://github.com/comicrelief/comicrelief-contentful/issues/631#event-3251169036

Nav arrow Apply for funding 

---

src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessage/SingleMessage.md

fix: check for iOS before attemtping to autotrigger video (iOS 12 doesn't like that)

---

src/components/Organisms/Donate/Form/Form.js

Type: patch
https://deploy-preview-278--cr-component-library.netlify.app/#!/Donate

Remove text donate widget

---

src/components/Molecules/SearchInput/SearchInput.js
src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js

Search button ay11

---

src/components/Molecules/SearchInput/SearchInput.js
src/components/Molecules/SearchInput/SearchInput.style.js
src/components/Molecules/SearchInput/SearchInput.test.js

Issue:
• This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit buttons are INPUT elements with type attribute "submit" or "image", or BUTTON elements with type "submit" or omitted/invalid.

Improve search a11y

---

src/components/Atoms/TextInputWithDropdown/TextInputWithDropdown.style.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap

fix: Z-index helper was being used incorrectly

---

src/components/Atoms/Select/Select.js
src/components/Atoms/Select/Select.test.js

(like the placeholder on a text input)

Add option for select input description to have grey text

---

src/components/Organisms/MarketingPreferences/MarketingPreferences.js
src/components/Organisms/MarketingPreferences/TextInput.js

In line with react-hook-form recommendations

Converting marketing preferences inputs to be 'uncontrolled' 

---

src/components/Organisms/Membership/Membership.test.js
src/components/Organisms/Membership/MoneyBox/MoneyBox.js

Fix Membership money buy input height

---

src/components/Molecules/Promo/Promo.js
src/components/Molecules/Promo/Promo.md
src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/Promo.test.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap
src/index.js

feat: update promo

---

package.json
src/components/Organisms/MarketingPreferences/MarketingPreferences.md
yarn.lock

Type: patch
Closes https://github.com/comicrelief/component-library/issues/329

Upgrade react-hook-form to v6

---

package.json
src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/Select/Select.js
src/components/Atoms/Select/Select.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js
src/theme/crTheme/colors.js
yarn.lock

feat: add grey colour ally update snaps

---

src/components/Molecules/Banner/Banner.js
src/components/Molecules/Banner/Banner.md
src/components/Molecules/Banner/Banner.test.js
src/components/Molecules/Banner/__snapshots__/Banner.test.js.snap

Banner component

---

src/components/Molecules/Promo/Promo.js
src/components/Molecules/Promo/Promo.md

Fixes https://github.com/comicrelief/comicrelief-contentful/issues/743

Update promo copy

---

src/components/Molecules/Promo/Promo.js
src/components/Molecules/Promo/Promo.md
src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/Promo.test.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap
src/components/Molecules/SingleMessageDS/SingleMessageDs.style.js
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessage.test.js.snap
src/theme/crTheme/buttonColors.js

Review DS pages

---

src/components/Molecules/Accordion/Accordion.js
src/components/Molecules/Accordion/Accordion.md
src/components/Molecules/Accordion/Accordion.test.js
src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap
src/components/Molecules/SingleMessageDS/SingleMessage.test.js
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessage.test.js.snap

Fixes #321 
https://deploy-preview-327--cr-component-library.netlify.app/#!/Accordion/1

Accordion Component

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/Input.md
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

E.g. for money fields that need a currency symbol
Type: patch
Fixes #362

feat: Add optional 'prefix' prop to Input

---

src/components/Organisms/MarketingPreferences/MarketingPreferences.js

Clearer copy provided by fundraising

feat: Update marketing prefs text when 'no' selected

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/Input.md
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

Type: patch
I need to add a span in `label` for styling purposes.

Markup Input label

---

src/components/Organisms/MarketingPreferences/MarketingPreferences.js

This change was requested in #fundraising-pack

feat: Update the marketing preferences text when a user selects 'no'

---

src/components/Molecules/ShareButton/ShareButton.js
src/utils/ShareButton/shareTracking.js
src/utils/ShareButton/shareUrlHelper.js

Type: patch
Reviewed by Hiral. Track is working

Social event tracking

---

src/components/Molecules/Typeahead/Typeahead.js

It's necessary to call the debounced function for every event, not just when there are enough characters, and reset the state values as part of this.
Otherwise, if you type something and then quickly delete it, you'll get options showing for the query string that was deleted.
Type: patch

fix: Slight bug with Typeahead debouncing

---

src/components/Molecules/Promo/Promo.js
src/components/Molecules/Promo/Promo.md
src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/Promo.test.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap

Fixes #386
https://deploy-preview-385--cr-component-library.netlify.app/#!/Promo

Promo variations

---

cypress/integration/components/Organisms/Header.spec.js
src/components/Organisms/Header/Nav/Nav.js
src/components/Organisms/Header/Nav/Nav.style.js

Type: patch
Fixes #
- Briefly describe the changes in this PR
- Do you have some test asserting this behavior?

fix: nav menu mobile

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/Input.md
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

Tidying up `<Input>` a little as noticed some weird stuff going on when `showLabel` is false
I.e. we had this
```
const TextLabel = styled(Text)`	
visibility: ${({ showLabel }) => !showLabel && hideVisually};	
`;
```
But rather than being 'hidden', the value of `hideVisually' is:
```
const hideVisually = css`
border: 0;
clip: rect(0 0 0 0);
clip-path: inset(50%);
height: 1px;
margin: -1px;
overflow: hidden;
padding: 0;
position: absolute;
white-space: nowrap;
width: 1px;
`;
```

fix: Input 'showLabel' prop css

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextArea/TextArea.js
src/components/Atoms/TextArea/TextArea.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/HeaderEsuWithIcon/__snapshots__/HeaderEsuWithIcon.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

Mucked up the position of the error message on `<Input/>`

fix: Input error message position

---

src/components/Molecules/Accordion/Accordion.js
src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap

Updated the Accordion component as I needed to be able to style it with a different background colour, (so added `rest` props which enables me to use it with `styled()`)
Also removed some unused code & tweaked the CSS slightly to make the whole bar clickable (i.e. including the padding)

feat: Accordion updates

---

src/components/Molecules/CardDs/CardDs.js
src/components/Molecules/CardDs/CardDs.md
src/components/Molecules/CardDs/CardDs.test.js

Type: patch
Icons on Cards DS button are props now instead by target Internal and external
https://deploy-preview-416--cr-component-library.netlify.app/#!/CardDs

feat: add icon prop cardds

---

src/components/Molecules/SingleMessageDS/SingleMessageDs.md

Just trying to trigger a new release as I forgot to add `feat` to the commit message

feat: add linkIcon prop to SingleMessageDs

---

src/components/Atoms/Input/Input.js

https://deploy-preview-430--cr-component-library.netlify.app/#!/Input/6

fix: input prefix zindex

---

src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap

Stacking on mobile. Image top content bottom.

feat: update promo mobile design

---

src/components/Molecules/SingleMessageDS/SingleMessageDs.js
src/components/Molecules/SingleMessageDS/SingleMessageDs.md
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap

Type: patch
Making CTA not required
https://deploy-preview-438--cr-component-library.netlify.app/#!/SingleMessageDs/5

feat: update smds video cta

---

.circleci/config.yml
package.json
yarn.lock

feat: upgrade no breaking modules

---

src/components/Molecules/SingleMessage/SingleMessage.js

Just needed to trigger a new release

feat: improve domain newtab Link functionality

---

src/components/Atoms/Link/Link.js
src/components/Organisms/Footer/Footer.js
src/components/Organisms/Footer/Footer.md
src/components/Organisms/Footer/Nav/Nav.js
yarn.lock

Type: patch
Fixes #450 
Okay, so as per my original solution, the real problem was that _any_ Footer link URL found in our whitelist would be opened in the same tab, and we don't _always_ want this (as per the Prefs centre)
I've added in an optional footer prop to allow this to be overridden as I can't see another way around this.

fix: allow whitelist overriding

---

package.json
src/components/Atoms/ButtonWithStates/ButtonWithStates.js
src/components/Atoms/ButtonWithStates/ButtonWithStates.md
src/components/Atoms/Link/Link.js
src/components/Molecules/Lookup/Lookup.js
src/components/Molecules/SimpleSchoolLookup/SimpleSchoolLookup.js
src/components/Molecules/SimpleSchoolLookup/SimpleSchoolLookup.md
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap
src/index.js
yarn.lock

https://deploy-preview-453--cr-component-library.netlify.app/#!/SimpleSchoolLookup

Simple School Lookup

---

cypress/integration/components/Atoms/MarketingPreferencesDSForm.spec.js
package.json
src/components/Organisms/MarketingPreferencesDS/_MarketingPrefsConfig.js
yarn.lock

As per discussions [here](https://github.com/comicrelief/comicrelief-contentful/pull/1102), yup-phone isn't fit for purpose

fix: replace yup-phone with custom validation in MPs

---

src/components/Molecules/SingleMessageDS/SingleMessageDs.style.js
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap

Type: patch
Fixes comicrelief.atlassian.net/browse/ENG-1675 (not linked so _this_ doesn't automatically close the Jira ticket)

fix: Promo and Card style fixes

---

src/components/Organisms/Donate/Form/Form.js

Fixes https://comicrelief.atlassian.net/browse/ENG-1685

fix: check moneybuy tally before using in Donate row

---

.eslintrc
src/components/Atoms/Logo/Logo.js
src/components/Atoms/Logo/Logo.test.js
src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
src/components/Organisms/Header/Header.style.js

Tweaks the nav logos to make use of available space and improve layout
cos it looks nicerer
[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-1784)

fix: resize CR logo and adjust spacing

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Donate.test.js
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap

Additional edits to the Donate widget sprint
Fundraising

feat: add 'chooseAmountText' prop to Donate widget

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Donate.style.js
src/components/Organisms/Donate/Form/PopUpComponent.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/theme/crTheme/colors.js

- Update default copy for pop up - https://comicrelief.atlassian.net/browse/ENG-1857
- Fix transparency background colour; only adding opacity when a non-transparent bg colour is chosen
To follow:
- ~~Mock ups on edits to pop up message, will feed into new styles~~ - Will keep this a separate PR, for sanity

fix: Donate widget updates 3

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/Form/PopUpComponent.js
src/components/Organisms/Donate/GivingSelector/GivingSelector.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap

More updates to Donate widget on CR.com
FR
https://comicrelief.atlassian.net/browse/ENG-1810

feat: Donate widget updates 4

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/GivingSelector/GivingSelector.js
src/theme/shared/size.js

Reverts comicrelief/component-library#509

fix: Revert "fix: use alternative Media Query function"

---

src/components/Organisms/Header/Nav/Nav.js
src/components/Organisms/Header/Nav/Nav.style.js
src/components/Organisms/Header/Nav/chevron-down.svg

Add cheveron-down icon to the navbar links that have a secondary dropdown menu.
Improve UI / Fundraising request.
https://comicrelief.atlassian.net/browse/ENG-1740

feat: add chevron svg

---

src/components/Molecules/Promo/Promo.style.js
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap

feat: Change breakpoint from small to medium to create more space for complex image
Fundraising
https://comicrelief.atlassian.net/browse/ENG-1731

feat: Change breakpoint from small to medium to create more space for complex image

---

src/components/Molecules/Box/Box.js
src/components/Molecules/Card/Card.js

refactoring prop for add roundedCorners option to Card and Box
to prevent any conflicts in a renamed CMS field
https://comicrelief.atlassian.net/browse/ENG-1680

feat: refactor Corners prop

---

src/index.js

quick fix to add export for Confetti component

fix: add missing Confetti main export

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Form/Form.js

Other Amount Message
Creating the ability to have a custom message appear when you choose a custom amount to donate on the Donate widget
FD
https://comicrelief.atlassian.net/browse/ENG-1984

feat: Other Amount Message

---

src/theme/crTheme/colors.js

Adds new colours for RND 23.
https://comicrelief.atlassian.net/browse/ENG-2030
RND 23
https://comicrelief.atlassian.net/browse/ENG-2030

feat: add rnd23 colors

---

src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/MoneyBox/MoneyBox.js
src/components/Organisms/Donate/MoneyBuy/MoneyBuy.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/Donate/dev-data/data.js
src/utils/Membership.js

Allow Donates row to show decimals properly
> "2.5" doesn't feel as user friendly
[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-2250)

feat: allow Donate row to show decimals properly

---

src/utils/whiteListed.js

Simplify Shorthand whitelist entry
So I can use it properly in CRcom
No ticket

fix: simplify Shorthand whitelist entry

---

cypress/integration/components/Organisms/Donate.spec.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Donate.style.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/Donate/dev-data/data-high-value.js

A mere padding tweak.
Just improves spacing for higher-value carts, updating one of the existing SB examples to illustrate it.
https://comicrelief.atlassian.net/browse/ENG-2267

fix: tweak styles for higher Donate row values

---

src/components/Molecules/Accordion/Accordion.js
src/components/Molecules/SingleMessage/SingleMessage.js
src/components/Molecules/SingleMessageDS/SingleMessageDs.md
src/components/Molecules/VideoBanner/VideoBanner.md
src/components/Organisms/Donate/Form/PopUpComponent.js

Fix errors in console.
Difficult to troubleshoot other issues with these kicking around.
https://comicrelief.atlassian.net/browse/ENG-2487

fix: errors in console

---

src/components/Molecules/SimpleSchoolLookup/SimpleSchoolLookup.js

Improves the default "no match" Schools Lookup msg, but also makes it an overridable prop.
Better signposting to ensure cleaner data
[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/ENG-2685)

feat: Schools FSU msg prop and new default value

---

src/components/Organisms/ImpactSlider/ImpactSlider.style.js

Removes an incorrect CSS rule; that's it.
Looks less crap
No ticket, just an issue that I didn't notice until it was in a CR build

fix: fix incorrect margins for Impact Slider

---

src/components/Organisms/ImpactSlider/ImpactSlider.js
src/components/Organisms/ImpactSlider/ImpactSlider.md

Add in Slider IDs for scrolling to
UX improvement
n/a

fix: add in Slider IDs for scrolling to

---

src/components/Organisms/ImpactSlider/_utils.js

fix: correct Slider forwarding URL

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Form/Form.js

Adds new optional props for some additional copy for either giving type:
Evening Standard kicking off about having to have some extra messaging specifically on the Monthly selection on the Winter Appeal page
https://comicrelief.atlassian.net/browse/ENG-2920

feat: add in additional copy fields to widget

---

src/components/Organisms/Donate/Donate.md

As discussed; previous merge didn't trigger a release; trying a 'fix' rather than a 'feat'

fix: attempt re-release

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Form/Form.js
src/components/Organisms/Donate/GivingSelector/GivingSelector.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/Donate/dev-data/data-monthly.js

Seeing build failures when trying to use a Monthly-only cart in a Donate widget, as the code as it stands presumes config ALWAYS exists for Single giving type.
This update fixes this assumption, but also adds a new prop, so that we can pass the cart's own 'default' giving type value directly to the widget if we want to.
Needed for forthcoming pages
No ticket

feat: handle Monthly-only Donate carts in widget

---

playwright/components/organisms/footer.spec.js
src/components/Organisms/Footer/Footer.md
src/components/Organisms/Footer/Footer.style.js

Upon updating the 'additional legal copy' in the CRcom, I noticed the longer char count looked bad on multiple lines, and here we are.
Looks better
No ticket for this per se

fix: improve footer legal copy layout

---

src/components/Organisms/Donate/Donate.js
src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/Donate.style.js
src/utils/_utils.js

Adds a new prop to override and control padding.
To make the NJAONS page look less barren
Not linking so it doesn't annoyingly mark it as 'done' once this is merged:
comicrelief.atlassian.net/browse/ENG-3091

feat: Padding options for Donate row

---

src/components/Molecules/CardDs/CardDs.js
src/components/Molecules/CardDs/CardDs.style.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap

Fixed 'Cards DS' right hand margin 
Content looks broken on UI after the changes it looks good and no scroll bar is needed at the bottom of the page
[ENG-2978]
[ENG-2978]: https://comicrelief.atlassian.net/browse/ENG-2978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: fixed CardDS margin

---

package.json
src/components/Molecules/Accordion/Accordion.js
src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap

fix: text alignment fix on Accordion

---

src/index.js

fix: Export WYMD Carousel

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.style.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.test.js

fix: missing Carousel bg colour

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.style.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.test.js

fix: WYMD Carousel design review updates

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.style.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.test.js
src/styleguide/data/data.js

fix: Carousel styletweaks

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.style.js
src/components/Organisms/WYMDCarousel/WYMDCarousel.test.js
src/styleguide/data/data.js

fix: WYND Carousel 7: Oh No, More Updates

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.js
src/components/Organisms/WYMDCarousel/_utils.js
src/styleguide/data/data.js

fix: Rename WYMD Carousel fields

---

src/components/Organisms/WYMDCarousel/WYMDCarousel.js
src/components/Organisms/WYMDCarousel/_utils.js
src/styleguide/data/data.js

fix: limit Carousel nodes as per CMS sync limit

---

src/components/Atoms/Link/Link.js
src/components/Atoms/Link/Link.md
src/components/Atoms/Link/Link.style.js
src/components/Atoms/Link/Link.test.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap
src/components/Molecules/Promo/__snapshots__/Promo.test.js.snap
src/components/Molecules/SingleMessage/__snapshots__/SingleMessage.test.js.snap
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap
src/components/Organisms/CookieBanner/CookieBanner.test.js

feat: add mobileColour prop to Link

---

src/components/Atoms/Icons/Arrow.js
src/components/Atoms/Icons/AtSign.js
src/components/Atoms/Icons/Chevron.js
src/components/Atoms/Icons/Download.js
src/components/Atoms/Icons/External.js
src/components/Atoms/Icons/Favourite.js
src/components/Atoms/Icons/Internal.js
src/components/Atoms/Link/Link.md
src/components/Atoms/Link/Link.test.js
src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap
src/components/Molecules/SingleMessageDS/__snapshots__/SingleMessageDs.test.js.snap
src/theme/crTheme/buttonColors.js

feat: Promo-related updates for Links and Icons

---

package.json

e.g.
or
Make sure the previous PR #655 is published.
It turns out `chore: ...` PRs don't result in a release (I think semantic release classifies this as a non-code change)

fix: Optimise dependencies

---

src/components/Organisms/MarketingPreferencesDS/_MarketingPrefsConfig.js

To make combining schemas easier in-situ

fix: export MP Validation fields too

---

package.json
src/components/Organisms/EmailSignUp/_TextInput.js
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/MarketingPreferencesDS/_CheckAnswer.js
src/components/Organisms/MarketingPreferencesDS/_MarketingPreferencesDS.js
src/components/Organisms/MarketingPreferencesDS/_TextInput.js
yarn.lock

Have issues integrating MPs within React-Payments in https://github.com/comicrelief/react-payments/pull/20, and this was the culprit; needed to bring everything inline with the versions and implementation

feat: Update react-hook-form

---

src/components/Organisms/MarketingPreferencesDS/_MarketingPrefsConfig.js

fix: update schema to updated Yup requirements

---

package.json
playwright/components/organisms/emailSignUpForm.spec.js
playwright/components/organisms/marketingPreferences.spec.js
yarn.lock

Can't believe I forgot to do this

fix: update yup

---

src/components/Organisms/Donate/Donate.md
src/components/Organisms/Donate/GivingSelector/GivingSelector.style.js
src/components/Organisms/Donate/MoneyBuy/MoneyBuy.js
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap

https://comicrelief.atlassian.net/browse/ENG-3436

fix: ENG-3436 update widget colour

---

src/components/Organisms/MarketingPreferencesDS/_MarketingPreferencesDS.js

fix: pass additional props to allow Styled Components to work on MPs

---

src/components/Organisms/MarketingPreferencesDS/MarketingPreferencesDS.style.js

fix: MP icon preload

---

playwright/components/molecules/accordian.spec.js
src/components/Molecules/Accordion/Accordion.js
src/components/Molecules/Accordion/Accordion.md

feat: optional Accordion prop to tweak padding

---

src/components/Atoms/Button/Button.js
src/components/Atoms/Button/Button.md

feat: Optional fullwidth prop for Button

---

src/theme/crTheme/Colors.md
src/theme/crTheme/colors.js
src/theme/srTheme/colors.js

e.g.
or
Adds in an exciting new shade of blue
[Add a link to the Jira ticket.](https://comicrelief.atlassian.net/browse/DF-128)

feat: adds blue_donate_interact colour

---

src/components/Molecules/Lookup/Lookup.js

I'm adding tests to the Donate FE, and this button I can't target because it's within our CompLib. Adding here so it has a testID.
For the benefit of adding tests
[DF-182]
[DF-182]: https://comicrelief.atlassian.net/browse/DF-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Adds test ID to lookup button

---

src/components/Molecules/Lookup/Lookup.js

The last PR didn't have the right semantic label at the front, so the NPM auto-deploy didn't occur. This should prompt it to.

feat: DF-182 add test ids

---

src/components/Organisms/Header2025/Header2025.js
src/components/Organisms/Header2025/Header2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.style.js

fix: design review Nav2025 tweaks

---

src/components/Organisms/Header2025/Header2025.md
src/components/Organisms/Header2025/Header2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.style.js

fix: design review Nav tweaks 3

---

src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.style.js

Attemptign to address hover issues with the very narrow More item

fix: Yet more nav2025 tweaks

---

src/components/Organisms/Header2025/Header2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.style.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.style.js

fix: alignment and load fixes for Nav2025

---

src/components/Atoms/SocialIcons/Icon/Icon.js
src/components/Atoms/SocialIcons/__snapshots__/SocialIcons.test.js.snap
src/components/Molecules/ShareButton/ShareButton.test.js
src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap

Just a lil improvement to try and standardise this everywhere

feat: more consistent test data-attr in Footer

---

src/components/Atoms/Checkbox/Checkbox.js

fix: make sure label correllates with checkbox ID

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

e.g.
or
Fixes the width of new input error messages when imported into repos.
Layout Bug.
https://comicrelief.atlassian.net/browse/DF-302

fix: the width of new input error messages when imported into repos

---

src/components/Atoms/Link/Link.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Organisms/CookieBanner/CookieBanner.test.js
src/components/Organisms/Footer/Footer.js
src/components/Organisms/Footer/Footer.style.js
src/components/Organisms/Footer/FundraisingRegulatorLogo.js
src/components/Organisms/Footer/Nav/Nav.style.js
src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap

Wraps the FR badge provided in some code to match the designs [here](https://www.figma.com/design/gYRmaUfyZJAP06yMVQcHOn/Fundraiser-Footer-Logo?node-id=1-1221&t=SRSeCH4oS60MzHf1-1): 
Check it out here: https://deploy-preview-716--cr-component-library.netlify.app/#!/Footer/1
_(**nb**: the "badge error" from the FR site it links to is because the Component Library Netlify builds don't live on the  correct domain; I've added comicrelief.com, donation.comicrelief.com and donate.comicrelief.com, so it'll work fine in-situ._
User trust
https://comicrelief.atlassian.net/browse/ENG-3969

feat: ENG-3969: Fundraising Regulator footer logo

---

src/components/Organisms/Footer/Footer.js
src/components/Organisms/Footer/Footer.md
src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap

feat: make FR optional via prop

---

src/components/Organisms/EmailSignUp/_EmailSignUp.js

Add custom button text to Email Sign Up.
Adopt a Red Nose campaign.
https://comicrelief.atlassian.net/browse/ENG-4012

feat: Email Sign Up - add custom button text

---

src/components/Molecules/CardDs/CardDs.style.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap

Adjusts button positioning on Cards DS mobile view.
CR.com improvements.
https://comicrelief.atlassian.net/browse/ENG-3870

fix: button positioning on Cards DS mobile view.

---

src/components/Molecules/CardDs/CardDs.md
src/components/Molecules/CardDs/CardDs.style.js
src/components/Molecules/CardDs/__snapshots__/CardDs.test.js.snap

fix: 3870 button positioning cards ds mobile 2

---

src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.js
src/components/Organisms/Header2025/HeaderNav2025/HeaderNavItem2025.js
src/components/Organisms/Header2025/HeaderNav2025/MoreNav.js

fix: add missing link formatter to More Nav items

---

src/theme/crTheme/colors.js

Reorder colour list into some order. Sets out approach going forward.
This doesn't delete any colours but sets out what is working and what isn't.
Gives Curtis a chance to input at this stage if wants.
Fix colour list chaos.
https://comicrelief.atlassian.net/browse/ENG-4124

Colour Lists Stage 4 : clean up general and campaign naming of Colours List

---

src/components/Atoms/ErrorText/ErrorText.js
src/components/Atoms/ErrorText/ErrorText.md
src/components/Atoms/ErrorText/__snapshots__/ErrorText.test.js.snap
src/components/Atoms/Input/Input.js
src/components/Atoms/Select/Select.js
src/components/Atoms/TextArea/TextArea.js
src/components/Molecules/InfoBanner/InfoBanner.js
src/components/Molecules/InfoBanner/__snapshots__/InfoBanner.test.js.snap
src/components/Organisms/EmailSignUp/_EmailSignUp.js
src/components/Organisms/ImpactSlider/_ImpactMoneybuys.js
src/theme/crTheme/fontSizes.js

Updating Error message sizing (namely to match AARN Donate designs) as a global changed approved by Curtis

feat: DF-393: reduce input error fontsize

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Input/input.test.js
src/components/Atoms/TextInputWithDropdown/__snapshots__/TextInputWithDropdown.test.js.snap
src/components/Molecules/SchoolLookup/__snapshots__/SchoolLookup.test.js.snap
src/components/Molecules/SearchInput/SearchInput.test.js
src/components/Molecules/Typeahead/__snapshots__/Typeahead.test.js.snap
src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap
src/components/Organisms/EmailSignUp/__snapshots__/EmailSignUp.test.js.snap
src/components/Organisms/Membership/Membership.test.js

fix: DF-394: update Input field border colour

---

src/components/Atoms/Input/Input.js
src/components/Atoms/Select/Select.js
src/components/Atoms/Select/__snapshots__/Select.test.js.snap

fix: Sundry QA4 design review tweaks

---

src/components/Atoms/Link/Link.style.js
src/components/Atoms/Link/Link.test.js
src/components/Molecules/ArticleTeaser/ArticleTeaser.test.js
src/components/Molecules/InfoBanner/__snapshots__/InfoBanner.test.js.snap
src/components/Molecules/PartnerLink/PartnerLink.test.js
src/components/Molecules/SearchResult/__snapshots__/SearchResult.test.js.snap
src/components/Organisms/CookieBanner/CookieBanner.test.js
src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
src/components/Organisms/WYMDCarousel/__snapshots__/WYMDCarousel.test.js.snap
src/theme/crTheme/linkStyles.js

feat: update Link styles to use standard underline

---

src/components/Organisms/Header2025/HeaderNav2025/HeaderNav2025.style.js

fix: unbork Nav2025 styles

---

src/components/Molecules/Accordion/Accordion.md
src/theme/shared/global.css

fix: recreate Link styles in generic anchor
